clang++^
 -I "./" -I "./include/" -I "./include/animation/" -I "./include/scene/" -I "./include/entities/" -I "../" -I "../include/" -I "../include/bullet" -I "../libglfw3/include/" -I "../libimgui/include/" -I "../rtaudio/include/" -I "../SDKs/wgpu-dawn/include/" -I "../SDKs/ffmpeg/include/" -I "../SDKs/RtAudio/include/" -I "../SDKs/OpenAl/include/" -I "../SDKs/Bullet/include/"^
 -L "../lib/" -L "../SDKs/wgpu-dawn/lib/x64/" -L "../SDKs/ffmpeg/lib/" -L "../SDKs/OpenAl/lib/x64/" -L "../SDKs/Bullet/lib/x64/"^
 -luser32 -lgdi32 -lshell32 -ldxguid -lonecore -lmsvcrt -llibcmt -lstrmiids -lmfuuid -lavrt^
 -llibglfw3 -llibimgui -llibrtaudio -llibassimp -lwgpu -llibfreeimage -llibzlib -llibavutil -llibavcodec -llibswresample -llibavformat -llibswscale -llibopenal -lliblinearmath -llibbulletcollision -llibbulletdynamics^
 src/scene/Node.cpp^
 src/scene/BaseNode.cpp^
 src/scene/SceneNode.cpp^
 src/scene/CollisionNode.cpp^
 src/animation/BoneDescription.cpp^
 src/animation/Bone.cpp^
 src/animation/Animation.cpp^
 src/animation/AnimationState.cpp^
 src/animation/AnimatedModel.cpp^
 src/animation/AnimationController.cpp^
 src/Object.cpp^
 src/VideoReader.cpp^
 src/BinaryIO.cpp^
 src/Fade.cpp^
 src/Mouse.cpp^
 src/Keyboard.cpp^
 src/Material.cpp^
 src/Transform.cpp^
 src/Mesh.cpp^
 src/Model.cpp^
 src/ObjModel.cpp^
 src/AssimpModel.cpp^
 src/Camera.cpp^
 src/CharacterSet.cpp^
 src/Application.cpp^
 src/bullet_store.cpp^
 src/enemy_spawner.cpp^
 src/entities/Entity.cpp^
 src/entities/CollisionEntity.cpp^
 src/entities/Enemy.cpp^
 src/entities/Player.cpp^
 src/main.cpp^
 States/StateMachine.cpp^
 States/Wireframe.cpp^
 States/ImageBasedLighting.cpp^
 States/ShadowMapping.cpp^
 States/SkinnedMesh.cpp^
 States/ComputeParticleLogo.cpp^
 States/PrimitivePicking.cpp^
 States/StencilMask.cpp^
 States/DeferredRendering.cpp^
 States/VolumeRendering.cpp^
 States/OcclusionQuery.cpp^
 States/RenderBundles.cpp^
 States/NuklearGui.cpp^
 States/AudioDecode.cpp^
 States/VideoDecode.cpp^
 States/Cubes.cpp^
 States/Isometric.cpp^
 ../Shape/Capsule.cpp^
 ../Shape/Cube.cpp^
 ../Shape/Cylinder.cpp^
 ../Shape/Quad.cpp^
 ../Shape/Segment.cpp^
 ../Shape/Sphere.cpp^
 ../Shape/Spiral.cpp^
 ../Shape/Torus.cpp^
 ../Shape/TorusKnot.cpp^
 ../Shape/Shape.cpp^
 ../WebGPU/WgpContext.cpp^
 ../WebGPU/WgpTexture.cpp^
 ../WebGPU/WgpBuffer.cpp^
 ../WebGPU/WgpMesh.cpp^
 ../WebGPU/WgpModel.cpp^
 ../WebGPU/WgpBatchRenderer.cpp^
 ../WebGPU/WgpFontRenderer.cpp^
 ../WebGPU/WgpRenderer.cpp^
 ../Nuklear/NkContext.cpp^
 ../Nuklear/NkStyle.cpp^
 ../Nuklear/NkCalculator.cpp^
 ../Nuklear/NkNodeEditor.cpp^
 ../Nuklear/NkJoystick.cpp^
 ../Sound/SoftwareMixer.cpp^
 ../Sound/RtAudioPlayer.cpp^
 ../Sound/OpenALPlayer.cpp^
 ../Sound/SoundDevice.cpp^
 ../Sound/AudioDecoder.cpp^
 ../Sound/RtAudioEffect.cpp^
 ../Sound/OpenALEffect.cpp^
 ../Sound/SoundEffect.cpp^
 ../Video/RGBADecoder.cpp^
 ../Video/YUVDecoder.cpp^
 ../Video/VideoDecoder.cpp^
 ../Physics/Physics.cpp^
 ../Physics/DebugDrawer.cpp^
 -D_MD -D_DLL -O3 -flto -fuse-ld=lld -std=c++17 -D_CRT_SECURE_NO_WARNINGS^
 -Wno-return-type-c-linkage^
 -DNWASM -DNDEBUG -DFREEIMAGE_LIB -DWEBGPU_DAWN -DAL_LIBTYPE_STATIC^
 -o Examples.exe